# Generated by Django 4.0.4 on 2022-07-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_module',
            name='account_id',
            field=models.CharField(max_length=100),
        ),
    ]
